export const NOTIFICATION_TYPE = {
  GENERAL: 'GENERAL',
  SCHEDULE: 'SCHEDULE',
  SUBSTITUTE: 'SUBSTITUTE',
  REPUTATION: 'REPUTATION',
  POSTING_APPLICATION: 'POSTING_APPLICATION',
  CHAT: 'CHAT',
  WORKSPACE_INVITATION: 'WORKSPACE_INVITATION',
  JOIN_REQUEST: 'JOIN_REQUEST',
} as const

export type NotificationType =
  (typeof NOTIFICATION_TYPE)[keyof typeof NOTIFICATION_TYPE]
